version: 0.2

env:
  variables:
    TERRAFORM_VERSION: 0.12.26
    TERRAFORM_SHA256SUM: 607bc802b1c6c2a5e62cc48640f38aaa64bef1501b46f0ae4829feb51594b257

phases:
  install:
    commands:
      - 'export TERRAFORM_ZIP=terraform_"${TERRAFORM_VERSION}"_linux_amd64.zip'
      - 'export TERRAFORM_URL=https://releases.hashicorp.com/terraform/"${TERRAFORM_VERSION}"/"${TERRAFORM_ZIP}"'
      - 'wget "${TERRAFORM_URL}"'
      - 'echo "${TERRAFORM_SHA256SUM}  ${TERRAFORM_ZIP}" | sha256sum -c'
      - 'unzip "${TERRAFORM_ZIP}"'
      - './terraform --version'
  pre_build:
    commands:
      - './terraform init'
  build:
    commands:
      - './terraform apply -input=false -auto-approve'

